version: '3.8'

services:
  thymer:
    build: .
    restart: unless-stopped
    volumes:
      - thymer-data:/root/.config/tm
    environment:
      - THYMER_URL=${THYMER_URL}
      - THYMER_TOKEN=${THYMER_TOKEN}

    ports:
      - "${HTTPS_PORT:-19501}:19501"

volumes:
  thymer-data:
